host: myapp.cpm
secret: mysecret
disablexsrf: false
loglevel: debug
type: api
storage:
  type: inmemory
  FileStoragePath: ./db.txt
  host: localhost
  port: 3306
  username: root
  password: 12345
  dbname: test_auth
  users:
    - admin: 123
